---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: podreporter
  name: podreporter
  namespace: podreporter
spec:
  containers:
  - args: ["-namespace", "podreporter"]
    command:
      - /app/podreporter
    image: serger89/podreporter:0.1
    imagePullPolicy: Never
    name: podreporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File